# Site Info
title:              "Olle Green"
description:        "My projects over the years."
author_name:        "Olle Green"
logo_url:           https://avatars3.githubusercontent.com/u/51267708?s=460&v=4

# Site Settings
url:                https://ollegreen.github.io
baseurl:            /
permalink:          /:title # Post permalink
timezone:           Europe/Stockholm # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones
mathjax:            true  # enables support for mathjax - set to 'false' to disable

# Site Build
highlighter:        rouge
markdown:           kramdown
kramdown:
    input:          GFM
sass:
    style:          :compressed

# Other Params
include:            [ "robots.txt" ]
exclude:            [ "LICENSE", "README.md", "CNAME", "vendor", "Gemfile", "script" ]
plugins:
  - jekyll-sitemap



defaults:
  -
    scope:
      path:         ""
    values:
      layout:       "null"
  -
    scope:
      type:         "pages"
    values:
      layout:       "page"
  -
    scope:
      type:         "posts"
    values:
      layout:       "post"
